loading dữ liệu

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/covid19.csv')
df.head(10)

,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
5,5,Asia,Afghanistan,40409359.0,3/13/2022,2022-03-13T11:00:04+00:00,58.0,10042.0,1124.0,158356.0,4356.0,176039,1.0,189.0,7641.0,22351.0,903192.0
6,6,Asia,Afghanistan,40406958.0,3/13/2022,2022-03-13T00:00:03+00:00,58.0,10042.0,1124.0,158356.0,4357.0,176039,1.0,189.0,7641.0,22352.0,903192.0
7,7,Asia,Afghanistan,40404557.0,3/12/2022,2022-03-12T10:30:03+00:00,81.0,10032.0,1124.0,158302.0,4355.0,175974,1.0,189.0,7640.0,22338.0,902544.0
8,8,Asia,Afghanistan,40404557.0,3/11/2022,2022-03-11T13:45:04+00:00,368.0,9970.0,1124.0,158284.0,4353.0,175893,3.0,189.0,7639.0,22321.0,901852.0
9,9,Asia,Afghanistan,40402155.0,3/11/2022,2022-03-11T00:00:03+00:00,368.0,9970.0,1124.0,158284.0,4354.0,175893,3.0,189.0,7639.0,22322.0,901852.0

Thực hiện chỉnh sửa

điếm giá trị nan trong database

In [ ]:
df.isnull().values.sum()

260231

In [ ]:
df.isnull().sum()

index                  0
continent           1075
country                0
population         24012
day                    0
time                   0
cases_new          30487
cases_active        2773
cases_critical     44623
cases_recovered     3733
cases_1M_pop          22
cases_total            0
deaths_new         81677
deaths_1M_pop      27514
deaths_total        5679
tests_1M_pop       27976
tests_total        10660
dtype: int64

In [ ]:
df = pd.DataFrame(df)
df

,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,NaN,189.0,7651.0,22496.0,909246.0
1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,887,NaN,Zimbabwe,NaN,4/2/2020,2020-04-02T19:30:05+00:00,1.0,7.0,NaN,NaN,0.5,8,NaN,NaN,1.0,NaN,NaN
232228,888,NaN,Zimbabwe,NaN,3/31/2020,2020-03-31T06:45:05+00:00,2.0,6.0,NaN,NaN,0.5,7,NaN,NaN,1.0,NaN,NaN
232229,889,NaN,Zimbabwe,NaN,3/28/2020,2020-03-28T11:00:04+00:00,2.0,4.0,NaN,NaN,0.3,5,NaN,NaN,1.0,NaN,NaN
232230,890,NaN,Zimbabwe,NaN,3/27/2020,2020-03-27T08:00:05+00:00,NaN,2.0,NaN,NaN,0.2,3,1.0,NaN,1.0,NaN,NaN
232231,891,NaN,Zimbabwe,NaN,3/23/2020,2020-03-23T12:15:06+00:00,NaN,3.0,NaN,NaN,0.2,3,NaN,NaN,NaN,NaN,NaN

điền giá trị bằng 0

In [ ]:
df.fillna(0, inplace=True)
df

,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,0.0,189.0,7651.0,22496.0,909246.0
1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,887,0,Zimbabwe,0.0,4/2/2020,2020-04-02T19:30:05+00:00,1.0,7.0,0.0,0.0,0.5,8,0.0,0.0,1.0,0.0,0.0
232228,888,0,Zimbabwe,0.0,3/31/2020,2020-03-31T06:45:05+00:00,2.0,6.0,0.0,0.0,0.5,7,0.0,0.0,1.0,0.0,0.0
232229,889,0,Zimbabwe,0.0,3/28/2020,2020-03-28T11:00:04+00:00,2.0,4.0,0.0,0.0,0.3,5,0.0,0.0,1.0,0.0,0.0
232230,890,0,Zimbabwe,0.0,3/27/2020,2020-03-27T08:00:05+00:00,0.0,2.0,0.0,0.0,0.2,3,1.0,0.0,1.0,0.0,0.0
232231,891,0,Zimbabwe,0.0,3/23/2020,2020-03-23T12:15:06+00:00,0.0,3.0,0.0,0.0,0.2,3,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.reset_index(level=0, inplace=True)
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,0.0,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,232227,887,0,Zimbabwe,0.0,4/2/2020,2020-04-02T19:30:05+00:00,1.0,7.0,0.0,0.0,0.5,8,0.0,0.0,1.0,0.0,0.0
232228,232228,888,0,Zimbabwe,0.0,3/31/2020,2020-03-31T06:45:05+00:00,2.0,6.0,0.0,0.0,0.5,7,0.0,0.0,1.0,0.0,0.0
232229,232229,889,0,Zimbabwe,0.0,3/28/2020,2020-03-28T11:00:04+00:00,2.0,4.0,0.0,0.0,0.3,5,0.0,0.0,1.0,0.0,0.0
232230,232230,890,0,Zimbabwe,0.0,3/27/2020,2020-03-27T08:00:05+00:00,0.0,2.0,0.0,0.0,0.2,3,1.0,0.0,1.0,0.0,0.0
232231,232231,891,0,Zimbabwe,0.0,3/23/2020,2020-03-23T12:15:06+00:00,0.0,3.0,0.0,0.0,0.2,3,0.0,0.0,0.0,0.0,0.0

In [ ]:
print(df.to_string(index=False))

Buffered data was truncated after reaching the output size limit.

Đếm số lượng hàng và đong

In [ ]:
print('số lượng hàng có trong df l:', len(df.axes[0]))
print('số lượng cột có trong df l:', len(df.axes[1]))

số lượng hàng có trong df l: 232232
số lượng cột có trong df l: 18

làm thành list

In [ ]:
arr = df.columns.values
print(arr)
print(f'Type of arr is {type(arr)}')

['level_0' 'index' 'continent' 'country' 'population' 'day' 'time'
 'cases_new' 'cases_active' 'cases_critical' 'cases_recovered'
 'cases_1M_pop' 'cases_total' 'deaths_new' 'deaths_1M_pop' 'deaths_total'
 'tests_1M_pop' 'tests_total']
Type of arr is <class 'numpy.ndarray'>

In [ ]:
l = list(df.columns.values)
print(l)
print(f'Type of arr is {type(l)}')

['level_0', 'index', 'continent', 'country', 'population', 'day', 'time', 'cases_new', 'cases_active', 'cases_critical', 'cases_recovered', 'cases_1M_pop', 'cases_total', 'deaths_new', 'deaths_1M_pop', 'deaths_total', 'tests_1M_pop', 'tests_total']
Type of arr is <class 'list'>

Tên từng cột

In [ ]:
for i in range(17):
    print(f'Cột {i + 1}', l[i])

Cột 1 level_0
Cột 2 index
Cột 3 continent
Cột 4 country
Cột 5 population
Cột 6 day
Cột 7 time
Cột 8 cases_new
Cột 9 cases_active
Cột 10 cases_critical
Cột 11 cases_recovered
Cột 12 cases_1M_pop
Cột 13 cases_total
Cột 14 deaths_new
Cột 15 deaths_1M_pop
Cột 16 deaths_total
Cột 17 tests_1M_pop

liệt kê 10 dòng và cột df

In [ ]:
df.iloc[:10]

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,0.0,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
5,5,5,Asia,Afghanistan,40409359.0,3/13/2022,2022-03-13T11:00:04+00:00,58.0,10042.0,1124.0,158356.0,4356.0,176039,1.0,189.0,7641.0,22351.0,903192.0
6,6,6,Asia,Afghanistan,40406958.0,3/13/2022,2022-03-13T00:00:03+00:00,58.0,10042.0,1124.0,158356.0,4357.0,176039,1.0,189.0,7641.0,22352.0,903192.0
7,7,7,Asia,Afghanistan,40404557.0,3/12/2022,2022-03-12T10:30:03+00:00,81.0,10032.0,1124.0,158302.0,4355.0,175974,1.0,189.0,7640.0,22338.0,902544.0
8,8,8,Asia,Afghanistan,40404557.0,3/11/2022,2022-03-11T13:45:04+00:00,368.0,9970.0,1124.0,158284.0,4353.0,175893,3.0,189.0,7639.0,22321.0,901852.0
9,9,9,Asia,Afghanistan,40402155.0,3/11/2022,2022-03-11T00:00:03+00:00,368.0,9970.0,1124.0,158284.0,4354.0,175893,3.0,189.0,7639.0,22322.0,901852.0

In [ ]:
df.iloc[:10] [['cases_new','cases_1M_pop']]

   cases_new  cases_1M_pop
0      128.0        4377.0
1      126.0        4373.0
2      108.0        4369.0
3      180.0        4365.0
4      118.0        4360.0
5       58.0        4356.0
6       58.0        4357.0
7       81.0        4355.0
8      368.0        4353.0
9      368.0        4354.0

In [ ]:
df[df['cases_new'].isnull()]

Empty DataFrame
Columns: [level_0, index, continent, country, population, day, time, cases_new, cases_active, cases_critical, cases_recovered, cases_1M_pop, cases_total, deaths_new, deaths_1M_pop, deaths_total, tests_1M_pop, tests_total]
Index: []

In [ ]:
df[df['cases_active'].isnull()]

Empty DataFrame
Columns: [level_0, index, continent, country, population, day, time, cases_new, cases_active, cases_critical, cases_recovered, cases_1M_pop, cases_total, deaths_new, deaths_1M_pop, deaths_total, tests_1M_pop, tests_total]
Index: []

In [ ]:
df[df[['continent', 'country', 'population', 'day', 'time',
        'cases_new', 'cases_active', 'cases_critical',
        'cases_recovered', 'cases_1M_pop', 'cases_total',
        'deaths_new', 'deaths_1M_pop', 'deaths_total',
        'tests_1M_pop']].isnull().any(axis=1)]

Empty DataFrame
Columns: [level_0, index, continent, country, population, day, time, cases_new, cases_active, cases_critical, cases_recovered, cases_1M_pop, cases_total, deaths_new, deaths_1M_pop, deaths_total, tests_1M_pop, tests_total]
Index: []

In [ ]:
df[(df['cases_active']<1000)| (df['cases_active']>-1500)]

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,0.0,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,232227,887,0,Zimbabwe,0.0,4/2/2020,2020-04-02T19:30:05+00:00,1.0,7.0,0.0,0.0,0.5,8,0.0,0.0,1.0,0.0,0.0
232228,232228,888,0,Zimbabwe,0.0,3/31/2020,2020-03-31T06:45:05+00:00,2.0,6.0,0.0,0.0,0.5,7,0.0,0.0,1.0,0.0,0.0
232229,232229,889,0,Zimbabwe,0.0,3/28/2020,2020-03-28T11:00:04+00:00,2.0,4.0,0.0,0.0,0.3,5,0.0,0.0,1.0,0.0,0.0
232230,232230,890,0,Zimbabwe,0.0,3/27/2020,2020-03-27T08:00:05+00:00,0.0,2.0,0.0,0.0,0.2,3,1.0,0.0,1.0,0.0,0.0
232231,232231,891,0,Zimbabwe,0.0,3/23/2020,2020-03-23T12:15:06+00:00,0.0,3.0,0.0,0.0,0.2,3,0.0,0.0,0.0,0.0,0.0

In [ ]:
df[(df['cases_new']<1000)| (df['cases_new']>-1500)]

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,0.0,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,232227,887,0,Zimbabwe,0.0,4/2/2020,2020-04-02T19:30:05+00:00,1.0,7.0,0.0,0.0,0.5,8,0.0,0.0,1.0,0.0,0.0
232228,232228,888,0,Zimbabwe,0.0,3/31/2020,2020-03-31T06:45:05+00:00,2.0,6.0,0.0,0.0,0.5,7,0.0,0.0,1.0,0.0,0.0
232229,232229,889,0,Zimbabwe,0.0,3/28/2020,2020-03-28T11:00:04+00:00,2.0,4.0,0.0,0.0,0.3,5,0.0,0.0,1.0,0.0,0.0
232230,232230,890,0,Zimbabwe,0.0,3/27/2020,2020-03-27T08:00:05+00:00,0.0,2.0,0.0,0.0,0.2,3,1.0,0.0,1.0,0.0,0.0
232231,232231,891,0,Zimbabwe,0.0,3/23/2020,2020-03-23T12:15:06+00:00,0.0,3.0,0.0,0.0,0.2,3,0.0,0.0,0.0,0.0,0.0

In [ ]:
df[(df['cases_total']<1000)| (df['cases_total']>-1500)]

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,0.0,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,9858.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,232227,887,0,Zimbabwe,0.0,4/2/2020,2020-04-02T19:30:05+00:00,1.0,7.0,0.0,0.0,0.5,8,0.0,0.0,1.0,0.0,0.0
232228,232228,888,0,Zimbabwe,0.0,3/31/2020,2020-03-31T06:45:05+00:00,2.0,6.0,0.0,0.0,0.5,7,0.0,0.0,1.0,0.0,0.0
232229,232229,889,0,Zimbabwe,0.0,3/28/2020,2020-03-28T11:00:04+00:00,2.0,4.0,0.0,0.0,0.3,5,0.0,0.0,1.0,0.0,0.0
232230,232230,890,0,Zimbabwe,0.0,3/27/2020,2020-03-27T08:00:05+00:00,0.0,2.0,0.0,0.0,0.2,3,1.0,0.0,1.0,0.0,0.0
232231,232231,891,0,Zimbabwe,0.0,3/23/2020,2020-03-23T12:15:06+00:00,0.0,3.0,0.0,0.0,0.2,3,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.loc[1,'cases_active'] = 10129.0
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,0,0,Asia,Afghanistan,40418964.0,3/17/2022,2022-03-17T20:15:03+00:00,128.0,9698.0,1124.0,159569.0,4377.0,176918,0.0,189.0,7651.0,22496.0,909246.0
1,1,1,Asia,Afghanistan,40416563.0,3/17/2022,2022-03-17T08:00:04+00:00,126.0,10129.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0
2,2,2,Asia,Afghanistan,40414161.0,3/16/2022,2022-03-16T08:00:04+00:00,108.0,10008.0,1124.0,158917.0,4369.0,176571,1.0,189.0,7646.0,22434.0,906639.0
3,3,3,Asia,Afghanistan,40411760.0,3/15/2022,2022-03-15T09:15:03+00:00,180.0,10257.0,1124.0,158507.0,4365.0,176409,2.0,189.0,7645.0,22410.0,905633.0
4,4,4,Asia,Afghanistan,40409359.0,3/14/2022,2022-03-14T09:15:03+00:00,118.0,10129.0,1124.0,158429.0,4360.0,176201,1.0,189.0,7643.0,22372.0,904055.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232227,232227,887,0,Zimbabwe,0.0,4/2/2020,2020-04-02T19:30:05+00:00,1.0,7.0,0.0,0.0,0.5,8,0.0,0.0,1.0,0.0,0.0
232228,232228,888,0,Zimbabwe,0.0,3/31/2020,2020-03-31T06:45:05+00:00,2.0,6.0,0.0,0.0,0.5,7,0.0,0.0,1.0,0.0,0.0
232229,232229,889,0,Zimbabwe,0.0,3/28/2020,2020-03-28T11:00:04+00:00,2.0,4.0,0.0,0.0,0.3,5,0.0,0.0,1.0,0.0,0.0
232230,232230,890,0,Zimbabwe,0.0,3/27/2020,2020-03-27T08:00:05+00:00,0.0,2.0,0.0,0.0,0.2,3,1.0,0.0,1.0,0.0,0.0
232231,232231,891,0,Zimbabwe,0.0,3/23/2020,2020-03-23T12:15:06+00:00,0.0,3.0,0.0,0.0,0.2,3,0.0,0.0,0.0,0.0,0.0

sắp xếp cao thấp

In [ ]:
df = df.sort_values(by='cases_active', ascending=False)
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
202325,202325,768,North-America,USA,334109463.0,2/8/2022,2022-02-08T02:00:02+00:00,152244.0,29177106.0,19766.0,48252586.0,234529.0,78358516,1235.0,2780.0,928824.0,2746315.0,917569679.0
202324,202324,767,North-America,USA,334109463.0,2/8/2022,2022-02-08T02:15:02+00:00,153184.0,29175382.0,19760.0,48257639.0,234539.0,78361861,1251.0,2780.0,928840.0,2746392.0,917595612.0
202323,202323,766,North-America,USA,334109463.0,2/8/2022,2022-02-08T02:30:02+00:00,156100.0,29169424.0,19750.0,48272080.0,234565.0,78370387,1273.0,2780.0,928883.0,2746842.0,917745985.0
202322,202322,765,North-America,USA,334109463.0,2/8/2022,2022-02-08T02:45:02+00:00,156467.0,29163093.0,19570.0,48278782.0,234566.0,78370754,1269.0,2780.0,928879.0,2748038.0,918145547.0
202328,202328,771,North-America,USA,334109463.0,2/8/2022,2022-02-08T01:15:02+00:00,135541.0,29162428.0,19766.0,48210432.0,234358.0,78301311,1123.0,2779.0,928451.0,2741516.0,915966507.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129597,129597,189,Europe,Moldova,4020713.0,12/1/2021,2021-12-01T19:00:03+00:00,664.0,-9119.0,206.0,363774.0,90475.0,363774,29.0,2268.0,9119.0,549895.0,2210968.0
177399,177399,420,Africa,South-Africa,60161961.0,8/24/2021,2021-08-24T19:30:03+00:00,10346.0,-17611.0,546.0,2646609.0,45028.0,2708951,369.0,1329.0,79953.0,267554.0,16096581.0
23622,23622,207,Europe,Bosnia-and-Herzegovina,3252806.0,11/16/2021,2021-11-16T03:00:04+00:00,1562.0,-1096882.0,0.0,1349956.0,81514.0,265149,113.0,3712.0,12075.0,412952.0,1343252.0
23623,23623,208,Europe,Bosnia-and-Herzegovina,3252861.0,11/16/2021,2021-11-16T00:00:04+00:00,1562.0,-1096882.0,0.0,1349956.0,81513.0,265149,113.0,3712.0,12075.0,412945.0,1343252.0
23510,23510,95,Europe,Bosnia-and-Herzegovina,3249145.0,1/21/2022,2022-01-21T09:15:03+00:00,2969.0,-1268120.0,0.0,1581164.0,100640.0,326995,39.0,4294.0,13951.0,484684.0,1574810.0

In [ ]:
df = df.sort_values(by='cases_new', ascending=False)
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
202962,202962,1405,North-America,USA,333945370.0,1/8/2022,2022-01-08T01:45:02+00:00,848502.0,17433261.0,21935.0,42172140.0,181059.0,60463747,2025.0,2570.0,858346.0,2493120.0,832566015.0
202963,202963,1406,North-America,USA,333945370.0,1/8/2022,2022-01-08T01:30:02+00:00,848502.0,17433521.0,21895.0,42171880.0,181059.0,60463747,2025.0,2570.0,858346.0,2492547.0,832374616.0
202859,202859,1302,North-America,USA,333971837.0,1/13/2022,2022-01-13T04:45:02+00:00,814494.0,20672722.0,24824.0,42805090.0,192665.0,64344694,2269.0,2596.0,866882.0,2542414.0,849094742.0
202807,202807,1250,North-America,USA,333982423.0,1/15/2022,2022-01-15T02:45:02+00:00,804877.0,22271920.0,25624.0,43018500.0,198100.0,66162016,2139.0,2610.0,871596.0,2564199.0,856397497.0
202808,202808,1251,North-America,USA,333982423.0,1/15/2022,2022-01-15T02:30:03+00:00,801914.0,22275668.0,25560.0,43011797.0,198091.0,66159053,2131.0,2610.0,871588.0,2563397.0,856129378.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170695,170695,32,Africa,Seychelles,99337.0,2/18/2022,2022-02-18T00:00:04+00:00,0.0,804.0,0.0,37803.0,390247.0,38766,0.0,1601.0,159.0,0.0,0.0
170692,170692,29,Africa,Seychelles,99341.0,2/21/2022,2022-02-21T00:00:04+00:00,0.0,804.0,0.0,37803.0,390232.0,38766,0.0,1601.0,159.0,0.0,0.0
68020,68020,106,Africa,Gabon,2303943.0,12/30/2021,2021-12-30T22:30:03+00:00,0.0,2882.0,9.0,36740.0,17322.0,39910,0.0,125.0,288.0,642187.0,1479562.0
54899,54899,226,South-America,Ecuador,17979367.0,10/6/2021,2021-10-06T00:00:03+00:00,0.0,34269.0,759.0,443880.0,28419.0,510954,0.0,1825.0,32805.0,102908.0,1850217.0
153660,153660,607,South-America,Peru,33369044.0,5/15/2021,2021-05-15T03:45:03+00:00,0.0,87335.0,2681.0,1720665.0,56139.0,1873316,0.0,1957.0,65316.0,356664.0,11901521.0

In [ ]:
df = df.sort_values(by='cases_critical', ascending=False)
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
90834,90834,3569,Asia,India,1.381901e+09,8/22/2020,2020-08-22T19:30:06+00:00,70068.0,706690.0,2279900.0,2279900.0,2202.0,3043436,918.0,41.0,56846.0,24959.0,34491073.0
40074,40074,202,South-America,Chile,1.936538e+07,1/9/2022,2022-01-09T16:30:03+00:00,4020.0,49551.0,457460.0,1740614.0,94469.0,1829437,21.0,2028.0,39272.0,1440293.0,27891827.0
77359,77359,7,Europe,Greece,1.033684e+07,3/14/2022,2022-03-14T20:00:02+00:00,22682.0,203794.0,356364.0,2427867.0,257167.0,2658296,73.0,2577.0,26635.0,6701454.0,69271836.0
222498,222498,20941,North-America,USA,3.309123e+08,6/14/2020,2020-06-14T00:15:06+00:00,25095.0,1173356.0,258496.0,851135.0,6473.0,2142017,701.0,355.0,117526.0,73355.0,24274209.0
222500,222500,20943,North-America,USA,3.309070e+08,6/13/2020,2020-06-13T23:45:06+00:00,24858.0,1174422.0,258496.0,849834.0,6472.0,2141780,699.0,355.0,117524.0,73357.0,24274209.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171639,171639,366,Africa,Sierra-Leone,8.033022e+06,11/9/2020,2020-11-09T16:15:08+00:00,8.0,495.0,0.0,1812.0,296.0,2381,0.0,9.0,74.0,0.0,0.0
21745,21745,272,Asia,Bhutan,7.802620e+05,7/11/2021,2021-07-11T14:00:04+00:00,8.0,332.0,0.0,1933.0,2904.0,2266,0.0,1.0,1.0,1023468.0,798573.0
142559,142559,595,Africa,Niger,0.000000e+00,5/6/2020,2020-05-06T20:30:04+00:00,8.0,182.0,0.0,543.0,32.0,763,1.0,0.0,38.0,0.0,5375.0
189975,189975,76,Asia,Timor-Leste,1.357713e+06,1/27/2022,2022-01-27T00:00:04+00:00,8.0,17.0,0.0,19740.0,14642.0,19879,0.0,90.0,122.0,166732.0,226374.0
190676,190676,156,Africa,Togo,8.534187e+06,10/29/2021,2021-10-29T18:00:07+00:00,12.0,290.0,0.0,25504.0,3051.0,26036,0.0,28.0,242.0,63934.0,545625.0

In [ ]:
df = df.sort_values(by='deaths_new', ascending=False)
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
88503,88503,1238,Asia,India,1.392679e+09,6/10/2021,2021-06-10T00:00:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20954.0,29182072,6138.0,258.0,359695.0,265814.0,370193563.0
88501,88501,1236,Asia,India,1.392716e+09,6/10/2021,2021-06-10T04:00:03+00:00,93896.0,1177152.0,8944.0,27645225.0,20953.0,29182072,6138.0,258.0,359695.0,265807.0,370193563.0
88502,88502,1237,Asia,India,1.392716e+09,6/10/2021,2021-06-10T01:45:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20953.0,29182072,6138.0,258.0,359695.0,265807.0,370193563.0
88504,88504,1239,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:45:02+00:00,93645.0,1183226.0,8944.0,27638902.0,20954.0,29181821,6136.0,258.0,359693.0,265814.0,370193563.0
88505,88505,1240,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:15:03+00:00,89664.0,1179437.0,8944.0,27638902.0,20951.0,29177840,5944.0,258.0,359501.0,265814.0,370193563.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64153,64153,1016,Europe,Finland,0.000000e+00,4/7/2020,2020-04-07T06:45:04+00:00,249.0,1849.0,81.0,300.0,393.0,2176,-1.0,0.0,27.0,0.0,32800.0
48787,48787,1182,0,Cyprus,0.000000e+00,4/5/2020,2020-04-05T08:15:05+00:00,30.0,384.0,11.0,33.0,353.0,426,-2.0,0.0,9.0,0.0,0.0
186989,186989,2042,Europe,Switzerland,0.000000e+00,3/24/2020,2020-03-24T10:15:05+00:00,0.0,8547.0,141.0,131.0,1016.0,8795,-3.0,0.0,117.0,0.0,0.0
140613,140613,1573,0,Netherlands,0.000000e+00,3/25/2020,2020-03-25T13:45:05+00:00,852.0,6154.0,435.0,2.0,374.0,6412,-20.0,0.0,256.0,0.0,0.0
122337,122337,1496,Asia,Malaysia,0.000000e+00,3/29/2020,2020-03-29T15:45:03+00:00,150.0,2077.0,73.0,388.0,76.0,2470,-22.0,0.0,5.0,0.0,0.0

tạo thêm 1 dòng

In [ ]:
D = {
    'continent': 'South America',
    'country': 'Brazil',
    'population': 213993437,
    'day': '2023-01-06',
    'time': '16:00',
    'cases_new': 1200,
    'cases_active': 1500,
    'cases_critical': 25,
    'cases_recovered': 8000,
    'cases_1M_pop': 1000,
    'cases_total': 12000,
    'deaths_new': 40,
    'deaths_1M_pop': 2,
    'deaths_total': 300,
    'tests_1M_pop': 15000
}
Dn= pd.DataFrame(df, index=[1])
df = pd.concat([df,Dn], ignore_index=True)
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,88503,1238,Asia,India,1.392679e+09,6/10/2021,2021-06-10T00:00:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20954.0,29182072,6138.0,258.0,359695.0,265814.0,370193563.0
1,88501,1236,Asia,India,1.392716e+09,6/10/2021,2021-06-10T04:00:03+00:00,93896.0,1177152.0,8944.0,27645225.0,20953.0,29182072,6138.0,258.0,359695.0,265807.0,370193563.0
2,88502,1237,Asia,India,1.392716e+09,6/10/2021,2021-06-10T01:45:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20953.0,29182072,6138.0,258.0,359695.0,265807.0,370193563.0
3,88504,1239,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:45:02+00:00,93645.0,1183226.0,8944.0,27638902.0,20954.0,29181821,6136.0,258.0,359693.0,265814.0,370193563.0
4,88505,1240,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:15:03+00:00,89664.0,1179437.0,8944.0,27638902.0,20951.0,29177840,5944.0,258.0,359501.0,265814.0,370193563.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232228,48787,1182,0,Cyprus,0.000000e+00,4/5/2020,2020-04-05T08:15:05+00:00,30.0,384.0,11.0,33.0,353.0,426,-2.0,0.0,9.0,0.0,0.0
232229,186989,2042,Europe,Switzerland,0.000000e+00,3/24/2020,2020-03-24T10:15:05+00:00,0.0,8547.0,141.0,131.0,1016.0,8795,-3.0,0.0,117.0,0.0,0.0
232230,140613,1573,0,Netherlands,0.000000e+00,3/25/2020,2020-03-25T13:45:05+00:00,852.0,6154.0,435.0,2.0,374.0,6412,-20.0,0.0,256.0,0.0,0.0
232231,122337,1496,Asia,Malaysia,0.000000e+00,3/29/2020,2020-03-29T15:45:03+00:00,150.0,2077.0,73.0,388.0,76.0,2470,-22.0,0.0,5.0,0.0,0.0
232232,1,1,Asia,Afghanistan,4.041656e+07,3/17/2022,2022-03-17T08:00:04+00:00,126.0,10129.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0

xóa hàng vừa thêm

In [ ]:
df = df.drop(1)
df

,level_0,index,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,88503,1238,Asia,India,1.392679e+09,6/10/2021,2021-06-10T00:00:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20954.0,29182072,6138.0,258.0,359695.0,265814.0,370193563.0
2,88502,1237,Asia,India,1.392716e+09,6/10/2021,2021-06-10T01:45:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20953.0,29182072,6138.0,258.0,359695.0,265807.0,370193563.0
3,88504,1239,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:45:02+00:00,93645.0,1183226.0,8944.0,27638902.0,20954.0,29181821,6136.0,258.0,359693.0,265814.0,370193563.0
4,88505,1240,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:15:03+00:00,89664.0,1179437.0,8944.0,27638902.0,20951.0,29177840,5944.0,258.0,359501.0,265814.0,370193563.0
5,88506,1241,Asia,India,1.392679e+09,6/9/2021,2021-06-09T16:45:03+00:00,89075.0,1178868.0,8944.0,27638902.0,20950.0,29177251,5924.0,258.0,359481.0,265814.0,370193563.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232228,48787,1182,0,Cyprus,0.000000e+00,4/5/2020,2020-04-05T08:15:05+00:00,30.0,384.0,11.0,33.0,353.0,426,-2.0,0.0,9.0,0.0,0.0
232229,186989,2042,Europe,Switzerland,0.000000e+00,3/24/2020,2020-03-24T10:15:05+00:00,0.0,8547.0,141.0,131.0,1016.0,8795,-3.0,0.0,117.0,0.0,0.0
232230,140613,1573,0,Netherlands,0.000000e+00,3/25/2020,2020-03-25T13:45:05+00:00,852.0,6154.0,435.0,2.0,374.0,6412,-20.0,0.0,256.0,0.0,0.0
232231,122337,1496,Asia,Malaysia,0.000000e+00,3/29/2020,2020-03-29T15:45:03+00:00,150.0,2077.0,73.0,388.0,76.0,2470,-22.0,0.0,5.0,0.0,0.0
232232,1,1,Asia,Afghanistan,4.041656e+07,3/17/2022,2022-03-17T08:00:04+00:00,126.0,10129.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0

đổi name

In [ ]:
df = df.rename(columns={'index': 'stt'})
df

,level_0,stt,continent,country,population,day,time,cases_new,cases_active,cases_critical,cases_recovered,cases_1M_pop,cases_total,deaths_new,deaths_1M_pop,deaths_total,tests_1M_pop,tests_total
0,88503,1238,Asia,India,1.392679e+09,6/10/2021,2021-06-10T00:00:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20954.0,29182072,6138.0,258.0,359695.0,265814.0,370193563.0
2,88502,1237,Asia,India,1.392716e+09,6/10/2021,2021-06-10T01:45:02+00:00,93896.0,1183475.0,8944.0,27638902.0,20953.0,29182072,6138.0,258.0,359695.0,265807.0,370193563.0
3,88504,1239,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:45:02+00:00,93645.0,1183226.0,8944.0,27638902.0,20954.0,29181821,6136.0,258.0,359693.0,265814.0,370193563.0
4,88505,1240,Asia,India,1.392679e+09,6/9/2021,2021-06-09T18:15:03+00:00,89664.0,1179437.0,8944.0,27638902.0,20951.0,29177840,5944.0,258.0,359501.0,265814.0,370193563.0
5,88506,1241,Asia,India,1.392679e+09,6/9/2021,2021-06-09T16:45:03+00:00,89075.0,1178868.0,8944.0,27638902.0,20950.0,29177251,5924.0,258.0,359481.0,265814.0,370193563.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232228,48787,1182,0,Cyprus,0.000000e+00,4/5/2020,2020-04-05T08:15:05+00:00,30.0,384.0,11.0,33.0,353.0,426,-2.0,0.0,9.0,0.0,0.0
232229,186989,2042,Europe,Switzerland,0.000000e+00,3/24/2020,2020-03-24T10:15:05+00:00,0.0,8547.0,141.0,131.0,1016.0,8795,-3.0,0.0,117.0,0.0,0.0
232230,140613,1573,0,Netherlands,0.000000e+00,3/25/2020,2020-03-25T13:45:05+00:00,852.0,6154.0,435.0,2.0,374.0,6412,-20.0,0.0,256.0,0.0,0.0
232231,122337,1496,Asia,Malaysia,0.000000e+00,3/29/2020,2020-03-29T15:45:03+00:00,150.0,2077.0,73.0,388.0,76.0,2470,-22.0,0.0,5.0,0.0,0.0
232232,1,1,Asia,Afghanistan,4.041656e+07,3/17/2022,2022-03-17T08:00:04+00:00,126.0,10129.0,1124.0,159234.0,4373.0,176743,2.0,189.0,7651.0,22463.0,907896.0

tính sai biệt

In [ ]:
df['cases_new'].diff().max()

770357.0

In [ ]:
df['cases_active'].diff().max()

29141884.0

In [ ]:
df['cases_critical'].diff().max()

2260807.0

In [ ]:
df['cases_recovered'].diff().max()

56509702.0

In [ ]:
df['cases_1M_pop'].diff().max()

696111.0

In [ ]:
df['cases_total'].diff().max()

81198937.0

In [ ]:
df['deaths_new'].diff().max()

24.0

In [ ]:
df['deaths_1M_pop'].diff().max()

6270.0

In [ ]:
df['deaths_total'].diff().max()

993423.0

In [ ]:
df['tests_1M_pop'].diff().max()

21692332.0

In [ ]:
df['tests_total'].diff().max()

968470345.0

Tạo list để lưu các giá trị sai biệt

In [ ]:
columns_to_diff = ['cases_new', 'deaths_new', 'tests_total', 'cases_active', 'cases_recovered']
max_continent = []
for c in df['continent'].unique():
    continent_data = df[df['continent'] == c]
    continent_diff = continent_data[columns_to_diff].diff().max().max()
    max_continent.append(continent_diff)

max_continent_dict = dict(zip(df['continent'].unique(), max_continent)) # Use df instead of d
df['max_continent'] = df['continent'].map(max_continent_dict) # Assign to df
print(df.head())
continent_data = pd.DataFrame(df['max_continent'])
print(continent_data.head(5))
d= df.drop(['max_continent'], axis=1)

   level_0   stt continent country    population        day  \
0    88503  1238      Asia   India  1.392679e+09  6/10/2021
2    88502  1237      Asia   India  1.392716e+09  6/10/2021
3    88504  1239      Asia   India  1.392679e+09   6/9/2021
4    88505  1240      Asia   India  1.392679e+09   6/9/2021
5    88506  1241      Asia   India  1.392679e+09   6/9/2021

                        time  cases_new  cases_active  cases_critical  \
0  2021-06-10T00:00:02+00:00    93896.0     1183475.0          8944.0
2  2021-06-10T01:45:02+00:00    93896.0     1183475.0          8944.0
3  2021-06-09T18:45:02+00:00    93645.0     1183226.0          8944.0
4  2021-06-09T18:15:03+00:00    89664.0     1179437.0          8944.0
5  2021-06-09T16:45:03+00:00    89075.0     1178868.0          8944.0

   cases_recovered  cases_1M_pop  cases_total  deaths_new  deaths_1M_pop  \
0       27638902.0       20954.0     29182072      6138.0          258.0
2       27638902.0       20953.0     29182072      6138.0          258.0
3       27638902.0       20954.0     29181821      6136.0          258.0
4       27638902.0       20951.0     29177840      5944.0          258.0
5       27638902.0       20950.0     29177251      5924.0          258.0

   deaths_total  tests_1M_pop  tests_total  max_continent
0      359695.0      265814.0  370193563.0    780324156.0
2      359695.0      265807.0  370193563.0    780324156.0
3      359693.0      265814.0  370193563.0    780324156.0
4      359501.0      265814.0  370193563.0    780324156.0
5      359481.0      265814.0  370193563.0    780324156.0
   max_continent
0    780324156.0
2    780324156.0
3    780324156.0
4    780324156.0
5    780324156.0

lưu file

In [ ]:
d.to_csv(r'modified_data.csv', index=False)